when:
  branch:
    - main
  
steps:
  release:
    when:
      repo: gillesvink/circle-of-confusion
    image: rust
    commands:
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall release-plz
      - export CARGO_REGISTRY_TOKEN=$${CARGO_REGISTRY_TOKEN}
      - release-plz release --forge gitea --git-token $${CODEBERG_TOKEN}
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
      CARGO_REGISTRY_TOKEN:
        from_secret: cargo_registry_token

  pull_request:
    image: rust
    commands:
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall release-plz
      - release-plz release-pr --forge gitea --git-token $${CODEBERG_TOKEN}
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
