when:
  event: [push, manual]
  path:
    include: ["*.rs", "*.toml", "*.yaml", "*.py"]
steps:
  test_rust:
    image: rust
    commands:
      - apt update
      - apt install -y protobuf-compiler
      - cargo test --release


  test_python:
    image: ghcr.io/astral-sh/uv:debian
    commands:
      - apt update
      - apt install -y protobuf-compiler
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - . "$HOME/.cargo/env" 
      - rustup target add wasm32-unknown-unknown
      - uv run pytest
