name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-22.04
    container:
      image: rust:1.90-trixie
    steps:
      - name: Install packages
        run: |
          apt update
          apt install nodejs -y

      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test